import {
  amber,
  blue,
  deepPurple,
  grey,
  indigo,
  orange,
  pink,
  purple,
  red,
  yellow,
  green,
} from "@mui/material/colors";

export const customColor = {
  amber: {
    light: amber[100],
    secondary: amber[300],
    primary: amber[500],
    fade: amber[800],
    deep: amber[900],
  },
  blue: {
    light: blue[100],
    secondary: blue[300],
    primary: blue[500],
    fade: blue[800],
    deep: blue[900],
  },
  indigo: {
    light: indigo[100],
    secondary: indigo[300],
    primary: indigo[500],
    fade: indigo[800],
    deep: indigo[900],
  },
  deepPurple: {
    light: deepPurple[100],
    secondary: deepPurple[300],
    primary: deepPurple[500],
    fade: deepPurple[800],
    deep: deepPurple[900],
  },
  grey: {
    light: grey[100],
    secondary: grey[300],
    primary: grey[500],
    fade: grey[800],
    deep: grey[900],
  },
  green: {
    light: green[100],
    secondary: green[300],
    primary: green[500],
    fade: green[800],
    deep: green[900],
  },
  orange: {
    light: orange[100],
    secondary: orange[300],
    primary: orange[500],
    fade: orange[800],
    deep: orange[900],
  },
  pink: {
    light: pink[100],
    secondary: pink[300],
    primary: pink[500],
    fade: pink[800],
    deep: pink[900],
  },
  purple: {
    light: purple[100],
    secondary: purple[300],
    primary: purple[500],
    fade: purple[800],
    deep: purple[900],
  },
  red: {
    light: red[100],
    secondary: red[300],
    primary: red[500],
    fade: red[800],
    deep: red[900],
  },
  yellow: {
    light: yellow[100],
    secondary: yellow[300],
    primary: yellow[500],
    fade: yellow[800],
    deep: yellow[900],
  },
};
